Add 'linux' and 'linux-firmware' packages to pacstrap command

diff --git a/2_installation b/2_installation
--- a/2_installation
+++ b/2_installation
@@ -25,9 +25,10 @@ if ! swapon --show | grep --silent "${SWAP_FILE_PATH}"; then
   fi
 fi
 
-# https://wiki.archlinux.org/index.php/installation_guide#Install_the_base_packages
-print_section "Install the base packages"
-pacstrap "${ROOT_DIR}" base || die "Couldn't install 'base'."
+# https://wiki.archlinux.org/index.php/Installation_guide#Install_essential_packages
+print_section "Install essential packages"
+pacstrap "${ROOT_DIR}" base linux linux-firmware \
+  || die "Couldn't install 'base' package, Linux kernel and firmware for common hardware."
 
 # https://wiki.archlinux.org/index.php/installation_guide#Fstab
 print_section "Setup fstab"
